
---
output:
  pagedown::html_paged:
    toc: false
    number_sections: false
    css:
      - css/syllabuscss.css
      - https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
    self_contained: true
---

## Contact details

<table>
<tr>
<td>Course Location</td>
<td>On-line</td>
</tr>
<tr><td>Faculty</td>
<td>
<b>Aaron Conway RN, PhD</b>
<br />
155 College Street
<br />
Rm. 274
<br />
(416) 946-7112 <br /> Email: aaron.conway@utoronto.ca
</td>
</tr>
<tr>
<td>Office Hours</td>
<td>By appointment</td>
</tr>
<tr>
<td>Teaching assistant</td>
<td>
  Danielle Just, PhD student
<br />
Email: danielle.just@mail.utoronto.ca
<br /><br />
Rozina Somani, PhD student
<br />
rozina.somani@mail.utoronto.ca
</td>
</tr>
<tr>
<td>Course Website</td>
<td>
</td>
</tr>
<tr>
<td>Quercus resources</td>
<td>Quercus student guide
</td>
</tr>
</table>

## Course description

NUR1127 builds on and extends the content introduced in NUR1027 and focuses on specific research designs and approaches that explain phenomena and relationships, or involve interventions/actions. You will develop competence in critically appraising, interpreting and synthesizing results from individual research studies and research syntheses. Critical appraisal and interpretation of qualitative and quantitative approaches and mixed methods studies will be addressed.

## Course objectives

_The overall objectives of the course are to enable students to:_

1. Apply knowledge of approaches and rigour in research to address a variety of nursing and health care questions.
1. Understand and appreciate ethical issues associated with health care research.

_Specifically, students will develop the ability to:_

1. Interpret and critically appraise individual studies with different approaches and with a variety of research designs.
1. Interpret and critically appraise research syntheses (systematic reviews, meta-syntheses, clinical practice guidelines).
1. Synthesize research evidence to inform nursing and healthcare leadership practice.

## Course structure

Over 12 weeks, you will learn key information about how to find, appraise, and use research in your practice. Each week's learning activities will include: learning objectives, resources and content as well as online class discussion to help you understand and apply the concepts. Each week will begin on a Tuesday and end on the following Monday at 11:59pm.

## Course schedule

<table>
<thead>
<tr>
<th>Date</th>
<th>Week</th><th>Topic</th>
<th>Assessment</th></tr>
</thead>
<tbody>
<tr>
<td>Jan 5</td>
<td>Week 1</td>
<td>Grounded Theory</td>
<td></td>
</tr>
<tr>
<td>Jan 12</td>
<td>Week 2</td>
<td>Randomized studies of interventions</td>
<td></td>
</tr>
<tr>
<td>Jan 19</td>
<td>Week 3</td>
<td><tr>Systematic reviews of randomized controlled trials</tr>
<tr>&</tr>
<tr>Alternative types of systematic reviews</tr></td>
<td></td>
</tr>
<tr>
<td>Jan 26</td>
<td>Week 4</td>
<td>Non-randomized studies of interventions</td>
<td>
<strong>
  Judging the certainty of evidence from a randomized controlled
    trial (group assigned)
</strong>
</td>
</tr>
<tr>
<td>Feb 2</td>
<td>Week 5</td>
<td>Mixed methods</td>
<td>
<strong>
Judging the certainty of evidence from a systematic review and meta-analysis (group assigned)
</strong>
</td>
</tr>
<tr>
<td>Feb 9</td>
<td>Week 6</td>
<td>Model testing and cohort/case-control designs</td>
<td>
<strong>
    Judging the certainty of evidence from a non-randomized study of
    an intervention (group assigned)
</strong>
</td>
</tr>
<tr>
<td>Feb 16</td>
<td>Week 7</td>
<td>Reading week</td>
<td></td>
</tr>
<tr>
<td>Feb 23</td>
<td>Week 8</td>
<td>Economic evaluation</td>
<td></td>
</tr>
<tr>
<td>Mar 2</td>
<td></td>
<td>
<strong>
<center>
  Residency week <br></br> NO CLASS
</center>
</strong>
</td>
  <td></td>
</tr>
<tr>
<td>Mar 9</td>
<td>Week 9</td>
<td>Practice guidelines and recommendations</td>
<td>
<strong>
 Knowledge test Tuesday March 9th at 10:00 am
</strong>
</td>
</tr>
<tr>
<td>Mar 16</td>
<td>Week 10</td>
<td>No class</td>
<td></td>
</tr>
<tr>
<td>Mar 23</td>
<td>Week 11</td>
<td>Ethics in research</td>
<td>
<strong>
    Online Ethics Tutorial due Monday March 29 at 4:00 pm
</strong>
</td>
</tr>
<tr>
<td>Mar 30</td>
<td>Week 12</td>
<td>Machine learning and prediction</td>
<td>
<strong>
  Research summary and recommendations paper due Monday April 12 at
      9:00 am
</strong>
</td>
</tr>
</tbody>
</table>

# Reading


## Required textbooks

_Same as for NUR1027_

Craig, JV & Dowding, D. (2020). Evidence-Based Practice in Nursing (4th ed.) Churchill Livingstone Elsevier.

Gray, J.R., Grove, S.K. & Sutherland, S. (2017). The Practice of Nursing Research (8th ed.) St. Louis Missouri: Elsevier.

_Textbooks can be purchased in person at the U of T Bookstore (214 College St.) or ordered online through the <a target="_blank" href="http://www.uoftbookstore.com/"> bookstore</a>._

## Required readings/resources

Unless otherwise stated, all articles listed in the course [learning material](https://nur1127.netlify.com) are available electronically by clicking on the links provided or through the University of Toronto Libraries <a target="_blank" href="http://www.library.utoronto.ca">website</a>.


# Learning activities


## Discussion group

Participation in an asynchronous discussion group, found by clicking on "Discussions" in Quercus will give you an opportunity for further clarification and commentary on the key concepts and learning activities, through dialogue with your classmates, professor and teaching assistant. It is expected that students will regularly respond to questions and comments posed on the discussion board, and that posts will develop increasing depth and sophistication as the course progresses.



## Online activities

In addition to independent learning activities, there will be regular online group activities designed to create learning synergies, extend your critical thinking about the course material, and build a sense of community among students.



## Working in an online environment

How do I work and learn in an online environment?
The online environment provides increased flexibility in terms of when and where you engage in learning activities. However it can also present challenges, requiring a degree of self-discipline to ensure you are able to take advantage of group discussions and learn from the observations and insights of your colleagues, as well as the course faculty. Here are some tips to help you be successful in engaging in on-line learning:

- This is a relatively self-directed learning environment, so it is important to manage your time carefully.
- As is the case in all graduate programs (both in-class and on-line), the course requires a considerable amount of independent study, guided by the resources and learning activities provided each week. Be sure to complete the weekly learning activities, and to participate in the Discussion every week. This is where we will work through together any questions you have about the material you are studying.
- Organize your time to ensure that you can complete the weekly reading and other learning activities on time. It is critical that you do not get behind.
- While completing the weekly learning activities, compile a list of questions or concerns that arise so that you can seek help via your colleagues on the discussion board.


## Writing resources

We strongly recommend a visit to the <a target="_blank" href="http://writing.utoronto.ca/">University of Toronto Writing Centre Website</a>. This website has a wealth of information regarding academic writing including information about writing when English is not your first language, writing courses and workshops available for students, and information about using other Writing Centres at the University of Toronto. The “Writing Advice” tab contains a host of online writing support resources. Sample topics include: preparing an outline, revising an essay, developing coherent paragraphs, style and editing, grammar and punctuation, etc.

Other helpful writing websites include:

1.	<a target="_blank" href="http://www.hswriting.ca/">Health Sciences Writing Centre</a>
2.	<a target="_blank" href="http://www.writing.utoronto.ca/advice/using-sources/how-not-to-plagiarize">How to avoid plagiarism</a>
3. <a target="_blank" href="http://www.sgs.utoronto.ca/currentstudents/Pages/GCAC.aspx">Graduate Centre for Academic Communication</a>

# Assignment submission


## Appearance and editing of assignments

All written assignments should be carefully proofread and well edited. The required style manual for the formatting of essays and assignments at the Lawrence S. Bloomberg Faculty of Nursing is that of the American Psychological Association (APA) 7th edition, which is described in:

_Publications Manual of the American Psychological Association (7th ed.). Washington: American Psychological Association, 2010._

The Purdue Online Writing Lab provides a helpful overview of the <a target="_blank" href="http://owl.english.purdue.edu/owl/resource/560/01/">General APA guidelines</a>.

## Submission

When submitting your assignment electronically, please name the file as follows: surname_first
initial_assignment[#].docx. Thus if your name is Mary Jones and you are submitting the first
written assignment, name the file jones_m_assignment1.docx.

## Cover page

Each paper should be presented with a formal cover page, which includes:

1. A title for the paper (Select a title that describes the substantive focus of the
   assignment). Please do not name your papers “Assignment 1,” “Search Assignment”,
   etc.)
1. Course number and title
1. Professor’s name
1. Student’s name (or initials, if you prefer) and student number

## References and appendices

Include a reference list of cited material using APA (7th edition) referencing format. For assignments that require Appendices, place these after the reference list.

## Other useful links

1. <a target="_blank" href="http://www.library.utoronto.ca">
     University of Toronto Library System
   </a>
2. <a target="_blank" href="http://gerstein.library.utoronto.ca/">
     Gerstein Science Information Centre
   </a>
3. <a target="_blank" href="http://www.sgs.utoronto.ca/">
     School of Graduate Studies
   </a>
4. <a target="_blank" href="https://guides.library.utoronto.ca/nursing-eresources">
     Nursing Resource Guide
   </a>

# Important University and Faculty policies

## Course drop date

March 1st, 2021 is the final date to drop Winter 2021 session courses without academic penalties. Click [here](https://bloomberg.nursing.utoronto.ca/current-students/sessional-dates-and-calendar#content2) for drop dates for 2020-21 courses.


## Grading of Written Assignments

All written assignments are subject to the grading regulations as outlined in the Lawrence S. Bloomberg Faculty of Nursing calendar and the School of Graduate Studies Calendar.

Late assignments after the due date will accrue a late penalty of 5% each day (including weekends).

## Submission of Assignments


For Online Courses: 

On the due date, please submit an electronic copy of your paper/assignment to the digital drop box in Turnitin using Quercus.  Your paper/assignment will NOT be evaluated until it is submitted to Turnitin using Quercus. 



## Writing an exam out of sequence or receiving an extension on an assignment

In an exceptional circumstance, e.g. death in family or medical illness, a student may be allowed to write an exam out of sequence or receive an extension on an assignment.

In response to the COVID-19 pandemic, U of T is temporarily suspending the need for a doctor’s note or medical certificate for any absence from academic participation in the University. All students have been instructed to self-report flu-like or cold symptoms **as well as any other health related absence** via ACORN in lieu of a note from a licensed health care provider. **Students still need to contact the instructor as soon as possible prior to the exam/assignment deadline to discuss the concern with the exam date or assignment deadline.** Please allow for leeway in these extraordinary times and reach out if you have additional questions. If a makeup sitting for an exam or an assignment deadline extension is granted, an alternate date needs to be set as close to the date of the original exam/assignment due date as possible. In case of an exam, you will be asked to complete the Declaration of Confidentiality for Students Sitting Tests/Examinations at Other Than the Regular Specified Time.

## Questions About Assignment

In the interest of fairness and transparency, please direct your questions about the paper to the proper discussion board on Quercus. If you do send an email to the instructor or teaching assistant, you may be encouraged to share this answer on the discussion board if the information is helpful to other learners in the course. Students are not permitted to submit a detailed, formal outline of the assignment for evaluation or instructor/TA feedback before the due date. As always, the instructor and/or TA would be happy to answer your questions via Quercus, email, telephone, or in person.

## Plagiarism & Academic Integrity

Turnitin is used in this course. Normally, students will be required to submit their course assignments to Turnitin.com for a review of textual similarity and detection of possible plagiarism. In doing so, students will allow their assignments to be included as source documents in the Turnitin.com reference database, where they will be used solely for the purpose of detecting plagiarism. The terms that apply to the University's use of the Turnitin.com service are described on the Turnitin.com web site. Students do have the option of handing in all their rough drafts and notes of their paper if they are opposed using to Turnitin. These students must approach their faculty teacher(s) in advance.

Academic integrity is essential to the pursuit of learning and scholarship in a university, and to ensuring that a degree from the University of Toronto is a strong reflection of each student’s individual academic achievement.

The University of Toronto Governing Council Code of Behaviour on Academic Matters
(University of Toronto Governing Council, 2019) is found <a target="_blank" href="http://www.governingcouncil.lamp4.utoronto.ca/wp-content/uploads/2016/07/p0701coboam-2015-2016pol.pdf">here</a>. The code outlines offences that constitute academic misconduct and processes for addressing academic offences. Section B.1 of the code (copied below) outlines academic offences.

It shall be an offence for a student knowingly:

(a) to forge or in any other way alter or falsify any document or evidence required by the University, or to utter, circulate or make use of any such forged, altered or falsified document, whether the record be in print or electronic form;
(b) to use or possess an unauthorized aid or aids or obtain unauthorized assistance in any academic examination or term test or in connection with any other form of academic work;
(c) to personate another person, or to have another person personate, at any academic examination or term test or in connection with any other form of academic work;
(d) to represent as one’s own any idea or expression of an idea or work of another in any academic examination or term test or in connection with any other form of academic work, i.e. to commit plagiarism (for a more detailed account of plagiarism, see Appendix "A") ;
(e) to submit, without the knowledge and approval of the instructor to whom it is submitted, any academic work for which credit has previously been obtained or is being sought in another course or program of study in the University or elsewhere;
(f) to submit any academic work containing a purported statement of fact or reference to a source which has been concocted. (Code of Behaviour on Academic Matters, 2019)

All suspected incidents of academic misconduct will be investigated following procedures outlined in the Code of Behaviour on Academic Matters (University of Toronto Governing Council, 2019).

## ProctorU Live+

Online exam(s) within this course [may] use online invigilation provided by ProctorU®, a live online proctoring service that allows completion of the assessment from an off-campus location. A highly trained human proctor will observe your completion of the exam using specialized software. Recordings will be made and held for a limited period of time in order to ensure academic integrity is maintained. The University of Toronto has an institutionally endorsed agreement with ProctorU that protects the privacy of the recordings, and other personal information.

Requirements: Students taking their examinations online will be proctored by ProctorU® throughout the duration of the exam. Access to a computer that can support remote recording is your responsibility as a student. You will need to ensure that you can complete the exam using a reliable computer with a webcam and microphone available, as well as a high-speed internet connection. Please note that you will be required to show your T-Card prior to beginning to write the exam. 

Detailed information and an opportunity to test your setup will be provided prior to the exam date. For additional information about online proctoring please see course information in Quercus, or visit UofT Online Proctoring Guidelines at https://teaching.utoronto.ca/ed-tech/online-learning/online-proctoring/ 

General Description for Using ProctorU Live+:  Students must first confirm their identity with photo ID with the human proctor. The proctor then closely monitors students and their immediate environment throughout the entire exam using webcams and remote desktop monitoring through high-speed Internet connections. All components of proctoring must be maintained for the duration of the exam. During the exam, the proctor may reach out to the student if they lose the ability to proctor the exam (camera view obstructed/loss of remote desktop view). If the proctor contacts the student during the exam through a pop-up message, voice, or a loud beep, the student is required to respond to the proctor. Failure to respond to the proctor to allow proctoring threatens the integrity of the exam. Non-compliance with exam protocols flagged by the invigilator will be investigated to determine whether an academic offence has been committed as per the University of Toronto Governing Council Code of Behaviour on Academic Matters. At the completion of the exam, a report of student exam-taking behaviours is generated and reviewed by the course instructor(s) and our IT staff. Exam grades will not be released to students until the integrity of the exam has been verified through ProctorU®, the course instructor(s), and our IT staff. 

Privacy and Information Security: The University of Toronto has a contract with ProctorU® that protects the privacy of the recordings, and other personal information. As you will be video recorded while writing the exam, you may want to consider preparing the background (room / walls) so that personal details you would not want visible are removed or take your exam in a room that you are comfortable showing on camera. It is recommended that students using ProctorU services remove the Chrome or Firefox extension after completion of the exam.

Retention of Video Content: Recordings captured via the ProctorU® system are available to the University and the instructor for one year after a recording is made. After this period of time has passed, recordings are purged.

For more information see ProctorU: Privacy and Security Information Notice for Students please see the following https://teaching.utoronto.ca/ed-tech/online-learning/online-proctoring/proctoru-privacy/ 



## Accessibility Statement

Students with diverse learning styles and needs are welcomed in this course. In particular, if you have a disability/health consideration that may require accommodations, please contact the Accessibility Services Office as soon as possible. The St. George Campus Accessibility Services staff (located in Robarts Library, First Floor) are available by appointment to assess specific needs, provide referrals and arrange appropriate accommodations (416)978-8060 or accessibility.services@utoronto.ca.

## Health and Wellness Centre

The <a target="_blank" href="http://healthandwellness.utoronto.ca/">Health & Wellness Centre</a> provides a variety of services for registered students including mental health services such as short-term individual counseling and group therapies for anxiety, low or depressed mood and resilience (e.g. Mindfulness-Based, Cognitive-Behavioural Therapy for Anxiety) and psychiatric medication services. Students also have access to counselling services on-site at the Faculty of Nursing through an Embedded Wellness Counsellor, Leah Direnfeld. Students can call 416-978-8030 to book an appointment.

## Student Evaluation of Courses

Student evaluation of courses is an essential component of our educational programs at the Lawrence S. Bloomberg Faculty of Nursing. Student feedback enables us to continue to improve our teaching effectiveness to enhance student learning.

The Lawrence S. Bloomberg Faculty of Nursing participates in the University of Toronto’s centralized ‘Student Evaluation of Courses’ system. Towards the end of this course, you will receive an email inviting you to complete an online evaluation of this course. The email will provide you with the specific information and links needed to access and complete course evaluation. Your ratings and comments will be anonymous but will be aggregated for summary across evaluations. Once a process has been established, summarized course evaluations will be made available within the faculty and university community. For more information about the University of Toronto policy about student evaluation of courses, please refer to the

<a
  target="_blank"
  href="http://www.governingcouncil.utoronto.ca/Assets/Governing+Council+Digital+Assets/Policies/PDF/ProvostiaStudentEval.pdf"
>
  website
</a>
.

## Technical Requirements for Online Academic Activities

There are technical requirements that will allow you to participate in the course. The course includes online webinars, online examinations, and assignments that are submitted online.

- Minimum Recommended Computer System Requirements
- Laptop or Desktop 4GB Ram Windows 10 or Mac OSX 10.12
- Screen Resolution of 1280 x 720 Webcam Headphones Microphone (Built-in, on headphones, or external) DSL or Cable Internet with 1.5 Mbps upload and download

If you have purchased your computer within the last 3-5 years you will likely have no trouble meeting these requirements. If your computer does not meet the minimum requirements you may have difficulty using some of the applications.

You will need the webcam to enable online proctoring for any proctored examinations. For proctored examinations we use the Proctor U service and technical requirements for that service can be found <a target="_blank" href="https://www.proctoru.com/auto-resource-center">here</a>. Most new laptops (within 3-5 years) have webcams built in. If you are using a desktop computer you may need to purchase a webcam. In addition, you will need a microphone (most webcams and laptops have built-in microphones) and a set of headphones such as the kind that come with mobile devices and smartphones.

In addition to the computer system requirements it is also recommended you have sufficiently fast Internet. Ensure you have DSL or Cable Internet with at least 1.5 Mbps download speed and at least 1.5 Mbps upload speed. Dial-up Internet is not recommended.
You can test your Internet speed by going to <a target="_blank" href="https://www.speedtest.net/">this website</a> and clicking “Go”.

In addition, it is important to note that some computer applications may be required to communicate throughout this course. Ensure you have:

- A PDF Reader (Adobe Reader, Preview, etc.)
- Word Processing Software (ie. Microsoft Office available free from U of T)
- Two web browsers (Firefox and Chrome are recommended)
- An updated Adobe Flashplayer as some systems still use this legacy product

Please note: If you are accessing the Internet through a large organization or using a work computer (e.g. a hospital) you may need to contact your organization’s IT department to arrange these downloads and confirm internet speed.

Please note, the university also provides free <a target="_blank" href="http://antivirus.utoronto.ca/index.php?page=students">antivirus software</a> to all students which is strongly recommended.

## Notice of video recording and sharing (including permissible download; prohibited re-use)

This course, including your participation, will be recorded on video and will be available to students in the course for viewing remotely and after each session.

Course videos and materials belong to your instructor, the University, and/or other source depending on the specific facts of each situation, and are protected by copyright. In this course, you are permitted to download session videos and materials for your own academic use, but you should not copy, share, or use them for any other purpose without the explicit permission of the instructor.

For questions about recording and use of videos in which you appear please contact your instructor.

## Equity, Diversity, and Inclusion

The University of Toronto is committed to equity, human rights and respect for diversity. All members of the learning environment in this course should strive to create an atmosphere of mutual respect where all members of our community can express themselves, engage with each other, and respect one another’s differences. U of T does not condone discrimination or harassment against any persons or communities.

# Evaluation methods


There will be five (5) assessments for NUR1127, including a:

- Group presentation (25%)
- Exam (25%)
- Ethics tutorial (5%)
- Written assignment (35%)
- Discussion board participation (10%)

## Group presentation - Judging the certainty of evidence from a research study

### Description

Students will work in small groups (4 people) to judge the certainty of evidence from a research study (using an example article from the syllabus for that week). Students will provide a slide presentation with voiceover (10 minutes maximum, 8-10 slides), to be posted on Voicethread and will facilitate an online discussion. The list of topics and dates for group presentations will be posted the first week of class.

Presentations must be posted by noon EST on the Monday of your scheduled week:

- Monday 27th Jan (RCT topic for discussion groups 1, 2, 3)
- Monday 3rd Feb (Systematic review topic for discussion groups 1, 2, 3)
- Monday 10th Feb (Non-randomized study of interventions topic for discussion groups 1, 2, 3)

**25% of final grade**

### Structure

The presentation should include a brief summary of the study approach (purpose, design, setting and sample, methods), presentation and interpretation of results, and of the certainty of evidence using the GRADE framework.

## Exam

### Description

This on-line examination will cover material presented in Weeks 1-7. It will include primarily multiple choice and some short-answer questions. On-line proctoring (Proctor U) will be used to support academic integrity.

**25% of final grade**

## Ethics tutorial

### Description

Complete the interactive on-line ethics tutorial from the Government of Canada <a href="http://tcps2core.ca/welcome">website</a>.

**5% of final grade**

## Written assignment

### Description

Students will compile, review, critically appraise, and synthesize research evidence about a topic or question, and prepare a summary of findings using the GRADE approach. The topic/question should address a practice situation that calls for a specific strategy or direction (in other words - an intervention). The literature review must include 3 published research studies. You are welcome to use the PICO question and search results from the assignment in NUR1027 if you wish. You will provide a summary of the studies (key features of each study, substantive results) and a summary of your critical appraisal, using the GRADE approach in the body of the paper. As such, you need to address the key elements of <a href="https://www.gradeworkinggroup.org/">GRADE</a>, being risk of bias, imprecision, indirectness, inconsistency and the completeness of reporting of research. The assignment will conclude with overall conclusions regarding the state of the evidence, and a GRADE recommendation to address the practice issue or situation.

**35% of final grade**

### Structure

Maximum 2000 words, plus table and references.

## Discussion board participation

### Description

- Active participation in assigned learning activities and discussions is required each week.
- The participation grade will be based on consistency of engagement in the weekly learning activities and discussions, and the quality of the comments and contributions.  
  **No due date - graded throughout the course**

**10% of final grade**

### The overall online participation grade will be assigned as follows:

_Excellent_

Regular and thoughtful contributions to learning activities and discussions push the conversation to a deeper level and encourage others to join.

_Acceptable_

Learning activity and discussion contributions are regular and keep the discussions on topic and help it to develop.

_Inadequate_

Contributions do not add to the development and progression of the discussion or learning activities. The student is missing from the discussion for several days, or regularly makes a first or last post without engaging with others.
